(setq load-path  (cons (expand-file-name "~/.emacs-lisp/") load-path))
(setq x-select-enable-clipboard t)
(require 'color-theme)
    (color-theme-initialize)
    (color-theme-tty-dark)
(add-to-list 'load-path "~/Downloads/matlab-emacs/matlab-emacs/matlab-emacs")
(require 'matlab-load)
(require 'column-marker)
(require 'linum)
